set_property IOSTANDARD LVCMOS33             [get_ports clk]
set_property IOSTANDARD LVCMOS33             [get_ports rst]
set_property PACKAGE_PIN G11                 [get_ports clk]
set_property PACKAGE_PIN B6                  [get_ports rst]
create_clock -period 20.000 -name clk [get_ports {clk}]


# Flash
set_property CFGBVS VCCO                     [current_design] 
set_property CONFIG_VOLTAGE 3.3              [current_design] 
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4               [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50  [current_design] 

set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[0]}]
set_property PACKAGE_PIN A5 [get_ports {seven_segment[7]}]
set_property PACKAGE_PIN B5 [get_ports {seven_segment[6]}]
set_property PACKAGE_PIN D3 [get_ports {seven_segment[0]}]
set_property PACKAGE_PIN C3 [get_ports {seven_segment[1]}]
set_property PACKAGE_PIN A4 [get_ports {seven_segment[2]}]
set_property PACKAGE_PIN A3 [get_ports {seven_segment[3]}]
set_property PACKAGE_PIN B3 [get_ports {seven_segment[4]}]
set_property PACKAGE_PIN A2 [get_ports {seven_segment[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property PACKAGE_PIN B2 [get_ports {sel[7]}]
set_property PACKAGE_PIN B1 [get_ports {sel[6]}]
set_property PACKAGE_PIN C5 [get_ports {sel[5]}]
set_property PACKAGE_PIN C4 [get_ports {sel[4]}]
set_property PACKAGE_PIN E4 [get_ports {sel[3]}]
set_property PACKAGE_PIN D4 [get_ports {sel[2]}]
set_property PACKAGE_PIN F3 [get_ports {sel[1]}]
set_property PACKAGE_PIN F2 [get_ports {sel[0]}]

 set_property PACKAGE_PIN M5 [get_ports s1]
 set_property PACKAGE_PIN M4 [get_ports s2]
 set_property PACKAGE_PIN P5 [get_ports s3]
 set_property PACKAGE_PIN N4 [get_ports s4]
 set_property IOSTANDARD LVCMOS33 [get_ports s1]
 set_property IOSTANDARD LVCMOS33 [get_ports s2]
 set_property IOSTANDARD LVCMOS33 [get_ports s3]
 set_property IOSTANDARD LVCMOS33 [get_ports s4]
 
set_property PACKAGE_PIN E11 [get_ports iic_scl]
set_property PACKAGE_PIN M10 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS33 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_sda]

set_property PACKAGE_PIN F12 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

 set_property IOSTANDARD LVCMOS33 [get_ports ds1302_ce]
 set_property PACKAGE_PIN A12 [get_ports ds1302_ce]
 set_property IOSTANDARD LVCMOS33 [get_ports ds1302_data]
 set_property PACKAGE_PIN A13 [get_ports ds1302_data]
 set_property IOSTANDARD LVCMOS33 [get_ports ds1302_sclk]
 set_property PACKAGE_PIN A10 [get_ports ds1302_sclk]
